# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    environment: staging

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Create env file
        run: |
          touch .env
          echo SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }} >> .env
          echo SERVER_PORT=${{ secrets.SERVER_PORT }} >> .env
          cat .env
      - run: npm i
      - run: npm test --if-present
      - run: pm2 restart ecosystem.config.js
